language: python
python:
  - 2.7
  - 3.5
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install opencl-headers
  - pip install pyopencl

install:
  - pip install tox tox-travis

script:
  - tox
