os:
  linux
  
language: python
python:
  - 2.7
  - 3.5
  
before_install:
  - sudo apt-get update
  - sudo apt-get install pocl-opencl-icd
  - pip install pyopencl

install:
  - pip install tox tox-travis

script:
  - tox
