build: false
platform: x64

environment:
  distutils_use_sdk: 1
  sdkver: "v7.0"

cache:
  - C:\Users\appveyor\.cache

init:
  - ps: $Env:sdkbin = "C:\Program Files\Microsoft SDKs\Windows\" + $Env:sdkver + "\Bin"
  - ps: $Env:sdkverpath = "C:/Program Files/Microsoft SDKs/Windows/" + $Env:sdkver + "/Setup/WindowsSdkVer.exe"
  - ps: $Env:path = "C:\Enthought\edm;" + $Env:sdkbin + ";" + $Env:path


install:
  # Just test to see if we have a reasonable Python.
  - ps: python -c "import sys; print(sys.executable)"

  # Install edm, needed so we can quickly install numpy.
  - ps: "(new-object net.webclient).DownloadFile('https://package-data.enthought.com/edm/win_x86_64/1.6/edm_1.6.1_x86_64.msi', 'edm.msi')"
  - ps: msiexec /qn /a edm.msi TARGETDIR=c:\
  - edm install -y numpy cython pytest mock h5py psutil

  # Install pysph related dependencies.
  - edm run -- pip install -r requirements.txt

  # Build pysph.
  - edm run -- python setup.py develop

test_script:
  # Run the tests.
  - edm run -- python -m pytest -v -m "not slow" --junit-xml=pytest.xml
